[package]
name = "rbctrl"
version = "0.1.0"
edition = "2024"
rust-version = "1.95.0"
readme = "README.md"


[profile.release]
opt-level = 3
lto = "fat"
debug = 0


[lints.clippy]
doc_lazy_continuation = "allow"


[target.'cfg(target_os = "macos")'.dependencies]
ort = { version = "2.0.0-rc.12", features = ["coreml", "ndarray", "tracing"] }


[dependencies]

# GStreamer
gstreamer =  "0.25.0"
gstreamer-app = "0.25.0"

# Communication
tokio = { version = "1.52.2", features = ["rt-multi-thread", "full"]}
kanal = { version = "0.1.1", features = ["async"] }
btleplug = { version = "0.11.8" }
uuid = { version = "1.23.1" }

# Logging
tracing = { version = "0.1.44" }
tracing-subscriber = { version = "0.3.23", features = ["registry", "env-filter"] }
tracing-test = { version = "0.2.6" }

# Computation
rayon = { version = "1.12.0" }

# CV
image = { version = "0.25.8", default-features = true, features = ["jpeg", "png"] }
imageproc = { version = "0.26.1", features = ["rayon"] }
opencv = { version = "0.98.2", features = ["objdetect"] }

# General
thiserror = { version = "2.0.18" }
